name: factory_asset_tree_flutter
description: Factory asset tree visualization
publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: ">=3.22.0 <4.0.0"
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  curl_logger_dio_interceptor: ^1.0.0

  # State management
  mobx: ^2.3.3+1
  flutter_mobx: ^2.2.1+1
  get_it: ^7.6.7
  injectable: ^2.4.1
  auto_route: ^7.9.2

  # Data
  equatable: ^2.0.5
  collection: ^1.18.0
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.4

  # UI
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Env
  flutter_flavorizr: ^2.2.1

  # Lint
  flutter_lints: ^3.0.1
  analyzer: ^6.4.1

  # Data
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mobx_codegen: ^2.6.0+1
  copy_with_extension_gen: ^5.0.4
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.6.1

  # Tests
  mockito: ^5.4.4
  covadge: ^0.0.1

  # UI
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/launcher/
    - assets/logo/
    - assets/splash/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  ide: idea
  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - flutter:flavors
    - flutter:app
    - flutter:targets
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    - assets:clean
    - ide:config

  flavors:
    stg:
      app:
        name: "[Stg]Asset Tree"
      android:
        applicationId: "com.dvosoftwarehouse.assettree.stg"
      ios:
        bundleId: "com.dvosoftwarehouse.assettree.stg"
    prod:
      app:
        name: "Enterprise Journal"
      android:
        applicationId: "com.dvosoftwarehouse.assettree"
      ios:
        bundleId: "com.dvosoftwarehouse.assettree"
